spring:
  application:
    name: api-book-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health