server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      host: "localhost"
      database: "book-service-db"
      username: "root"
      password: "secret"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

