server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka/